# Get products
GET api/v1/tch/products{?category_id, limit, page}

Parameters:
    + category_id (UUID, optional) - Category id
    + limit (int, optional) - Maximum results can be returned
        + Default: `5`
    + page (int) - The index of page
        + Default: `1`
Response: 200 (application/json)
    {
        "message": "Get products successfully."
        "status_code": 200,
        "data":
        {
            "categories":
            [{
                    "name": "Cà phê Việt Nam",
                    "products":
                    [
                        {
                            "id": 1,
                            "name": "Cà phê sữa đá",
                            "price": 20000,
                            "thumbnail": "ca_phe_sua_da.jpg",
                            "tag":
                            {
                                "name": "Bán chạy",
                                "color": "Đỏ"
                            }
                        }
                    ]
                }
            ]
        }
    }


# Get categories
GET api/v1/tch/categories/:category_id{?level}

Parameters:
    category_id: UUID, optional,
    level: int, optional
Response: 200 (application/json)
    {
            "message": "Get categories successfully."
            "status_code": 200,
            "data":
            [{
                "id": `sdgmdlkgmsd`
                "name": "Tất cả",
                "categories":
                [
                    {
                        "id": 1,
                        "name": "Cà phê",
                        "categories":
                        [
                            {
                                "id": `sdsdsds`
                                "name": "Cà phê Việt Nam",
                                "categories":[]
                            }
                        ]
                    },
                ],
            }]
    }


# Get product
Request
    path param: api/v1/tch/products/:product_id
Response 200 (application/json)
 {
     "message": "Get a product successfully."
     "status_code": 200,
     "data":
     {
        "id": `dsd121`,
        "name": "Cà phê Sữa đá",
        "price": 29000,
        "description": "Cà phê pha với sữa đặc"
        "images": ["ca_phe_sua_da.jpg"],
        "sizes":
        [{
            "id": `sd11`,
            "name": "Vừa",
            "price": 10000,
            "icon": "medium.jpg"
        }],
        "toppings":
        [{
            "id": `aawq1s`,
            "name": "Trân châu trắng",
            "price": 10000,
        }],
        "tag":
        {
            "id": `21sasq`,
            "name": "Bán chạy",
            "color": "Đỏ",
        }
     }
}

# Get cities
GET api/v1/tch/cities
Response 200 (application/json)
 {
    data: [
        {
            "id": `2dwdw`,
            "name": "TP. Hồ Chí Minh"
        },
        {
            "id": `324sd23`,
            "name": "Hà Nội"
        },
        {
            "id": `32dsw12`,
            "name": "Đà Nẵng"
        }
    ]
 }

# Get districts
GET api/v1/tch/cities/:city_id/districts
Parameters:
    city_id: UUID
Response 200 (application/json)
 {
    data: [
        {
            "id": `1tdas1`,
            "name": "Quận Tân Bình"
        },
        {
            "id": `23sdw12`,
            "name": "Quận Phú Nhuận"
        },
        {
            "id": `12wdf2`,
            "name": "Quận 3"
        }
    ]
 }

# Get stores
GET api/v1/tch/stores{?city_id, district, page}
Parameters:
    + city_id (UUID)
    + district (string, optional)
    + page (string, optional)
Response 200 (application/json)
 {
    data: {
        "total": 2,
        "stores": [
        {
            "id": `1tdas1`,
            "name": "HCM Lê Văn Sĩ",
            "images": ["levansi1.png", "levansi2.png"],
            "address": "1 Lê Văn Sĩ, Phường 1, Quận Tân Bình, Thành phố Hồ Chí Minh",
            "latitude": 121,21214,
            "longitude": 21,33213,
            "working_hour": "7:00 - 22:00",
            "facilities": [
                {
                    "name": "Mua mang đi",
                    "icon": "cart_icon"
                }
                {
                    "name": "Thân thiện với gia đình",
                    "icon": "kid_icon"
                }
            ]
        },
        {
            "id": `1tdas1`,
            "name": "HCM Hoa Hồng",
            "images": ["hoahong.png", "hoahong1.png"],
            "address": "1 Hoa Hồng, Phường 2, Quận Phú Nhuận, Thành phố Hồ Chí Minh",
            "working_hour": "7:00 - 22:00",
            "facilities": [
                {
                    "name": "Phục vụ tại chỗ",
                    "icon": "store_icon"
                }
                {
                    "name": "Thân thiện với gia đình",
                    "icon": "kid_icon"
                }
            ]
        }
    ]
 }


 # Get store
 GET api/v1/tch/stores/:store_id
 Parameters:
     + store_id (UUID)
 Response 200 (application/json)
  {
     data: {
            "id": `1tdas1`,
            "name": "HCM Hoa Hồng",
            "description": "Nhà cà phê toạ lạc tại đường Hoa Hồng"
            "images": ["hoahong.png", "hoahong1.png"],
            "address": "1 Hoa Hồng, Phường 2, Quận Phú Nhuận, Thành phố Hồ Chí Minh",
            "latitude": 121,21214,
            "longitude": 21,33213,
            "working_hours": [
                {
                    "day": "Chủ nhật",
                    "period": "8:00 - 21:00",
                },
                {
                    "day": "Thứ hai",
                    "period": "8:00 - 22:00",
                },
            ]
            "facilities": [
                {
                    "name": "Phục vụ tại chỗ",
                    "icon": "store_icon"
                }
                {
                    "name": "Thân thiện với gia đình",
                    "icon": "kid_icon"
                }
            ]
     }
  }

# Get directions from user location to specific store
GET api/v1/tch/stores/:store_id/directions{?ward, district, transport}
 Parameters:
     + store_id (required, UUID)
     + ward (required, string)
     + district (required, string)
     + transport (optional, string, default = 'driving')
 Response 200 (application/json)
  {
     data: {
            [{
              "duration": 603.833,
              "distance": 3184.425,
              "steps":[
                   "Turn right onto Hẻm 333/12 Lê Văn Sỹ.",
                   "Turn left to stay on Hẻm 333/12 Lê Văn Sỹ.",
                   "Your destination is on the right."
              ]},
              {
                "duration": 503.833,
                "distance": 1984.321,
                "steps": [
                    "Turn right onto Hoàng Văn Thụ.",
                    "Turn left onto Trương Quốc Dung.",
                    "Your destination is on the right."]
              }]
     }
  }

  Response 500 (application/json)
  {
      message: 'Server not available'
  }